"""adding Source tracking

Revision ID: 06404e99d96f
Revises: f2b7c91d4e60
Create Date: 2026-08-31 21:29:13.871949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06404e99d96f'
down_revision = 'f2b7c91d4e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=80), nullable=False, server_default="System"))
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=80), nullable=False, server_default="System"))

    with op.batch_alter_table('campaign_module_installation', schema=None) as batch_op:
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('installed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=80), nullable=False, server_default="System"))

    with op.batch_alter_table('loot_box', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=80), nullable=False, server_default="homebrew"))


    # Fix existing NULL campaign IDs before enforcing NOT NULL.
    op.execute("""
        UPDATE map_media_asset
        SET campaign_id = 5
        WHERE campaign_id IS NULL
    """)

    with op.batch_alter_table('map_media_asset', schema=None) as batch_op:
        batch_op.alter_column(
            'campaign_id',
            existing_type=sa.INTEGER(),
            existing_nullable=True,
            nullable=False
        )

    with op.batch_alter_table('npc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=80), nullable=False, server_default="unknown"))

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=80), nullable=False, server_default="System"))
        # NOTE: The uq_page_wiki_id_title UNIQUE constraint is created by the
        # ancestor migration 4d71b9e8c2af_unique_campaign_wiki_page_titles.py.
        # Do NOT recreate it here (alembic autogenerate re-emitted it, which
        # causes psycopg2.errors.DuplicateTable on databases where 4d71b9e8c2af
        # has already been applied).

    with op.batch_alter_table('street_lamp', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('street_lamp_route_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lamplighter_route', ['route_id'], ['id'])

    with op.batch_alter_table('world_atlas_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=80), nullable=False, server_default="System"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_atlas_location', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('street_lamp', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('street_lamp_route_id_fkey'), 'lamplighter_route', ['route_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('page', schema=None) as batch_op:
        # NOTE: The uq_page_wiki_id_title UNIQUE constraint is dropped by the
        # ancestor migration 4d71b9e8c2af_unique_campaign_wiki_page_titles.py;
        # do not drop it here.
        batch_op.drop_column('source')

    with op.batch_alter_table('npc', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('map_media_asset', schema=None) as batch_op:
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('loot_box', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('campaign_module_installation', schema=None) as batch_op:
        batch_op.alter_column('installed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
